# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1
_src_path: ../../ModernAppTemplate/backend
author_email: pvginkel@gmail.com
author_name: Pieter van Ginkel
backend_port: 5000
database_name: electronics_inventory
image_name: registry:5000/electronics-inventory
project_description: Electronics inventory management system
project_name: electronics-inventory
repo_url: https://github.com/pvginkel/ElectronicsInventory.git
s3_bucket_name: electronics-inventory-part-attachments
testing_port_offset: 100
use_database: true
use_oidc: true
use_s3: true
use_sse: true
