"""Add pin_pitch, input_voltage, and output_voltage fields to parts

Revision ID: 008
Revises: 007
Create Date: 2025-09-03 23:23:12.164163

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: str | None = '007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_attachments_part_id'), table_name='part_attachments')
    op.drop_index(op.f('ix_part_attachments_type'), table_name='part_attachments')
    op.drop_index(op.f('ix_part_locations_box_loc'), table_name='part_locations')
    op.drop_index(op.f('ix_part_locations_part_id'), table_name='part_locations')
    op.drop_constraint(op.f('part_locations_part_id_box_no_loc_no_key'), 'part_locations', type_='unique')
    op.create_unique_constraint('uq_part_location', 'part_locations', ['part_id', 'box_no', 'loc_no'])
    op.add_column('parts', sa.Column('pin_pitch', sa.String(length=50), nullable=True))
    op.add_column('parts', sa.Column('input_voltage', sa.String(length=100), nullable=True))
    op.add_column('parts', sa.Column('output_voltage', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_parts_cover_attachment_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_key'), table_name='parts')
    op.drop_index(op.f('ix_parts_type_id'), table_name='parts')
    op.drop_index(op.f('ix_quantity_history_part_id'), table_name='quantity_history')
    op.drop_index(op.f('ix_quantity_history_timestamp'), table_name='quantity_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quantity_history_timestamp'), 'quantity_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_quantity_history_part_id'), 'quantity_history', ['part_id'], unique=False)
    op.create_index(op.f('ix_parts_type_id'), 'parts', ['type_id'], unique=False)
    op.create_index(op.f('ix_parts_key'), 'parts', ['key'], unique=False)
    op.create_index(op.f('ix_parts_cover_attachment_id'), 'parts', ['cover_attachment_id'], unique=False)
    op.drop_column('parts', 'output_voltage')
    op.drop_column('parts', 'input_voltage')
    op.drop_column('parts', 'pin_pitch')
    op.drop_constraint('uq_part_location', 'part_locations', type_='unique')
    op.create_unique_constraint(op.f('part_locations_part_id_box_no_loc_no_key'), 'part_locations', ['part_id', 'box_no', 'loc_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_part_locations_part_id'), 'part_locations', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_locations_box_loc'), 'part_locations', ['box_no', 'loc_no'], unique=False)
    op.create_index(op.f('ix_part_attachments_type'), 'part_attachments', ['attachment_type'], unique=False)
    op.create_index(op.f('ix_part_attachments_part_id'), 'part_attachments', ['part_id'], unique=False)
    # ### end Alembic commands ###
