PRODUCT_CATEGORIES = [
  "Resistors",
  "Thermistors (NTC/PTC)",
  "Potentiometers",
  "Capacitors",
  "Inductors & Chokes",
  "Transformers",
  "Diodes (Rectifier/General)",
  "Schottky Diodes",
  "Zener Diodes",
  "Bridge Rectifiers",
  "Transient & ESD Protection (TVS/MOV/GDT)",
  "LEDs (Discrete)",
  "LED Strips & Drivers",
  "LED Matrices & Segment Displays",
  "Optocouplers",
  "BJTs",
  "MOSFETs",
  "Transistor Arrays & Drivers",
  "Linear & LDO Regulators",
  "DC-DC Converters (ICs & Modules)",
  "AC-DC Power Modules",
  "Power Management (PMICs/Supervisors)",
  "Battery Chargers (ICs & Modules)",
  "Battery Protection & BMS",
  "Batteries & Holders",
  "Wall Adapters & Power Bricks",
  "Crystals & Resonators",
  "Oscillators & Clock Generators",
  "Op-Amps",
  "Comparators",
  "Analog Switches & Multiplexers",
  "Data Converters (ADC/DAC)",
  "Voltage References",
  "Audio Amplifiers",
  "Audio Components (Mics/Speakers/Buzzers)",
  "IR Components (Emitters/Receivers)",
  "Camera Modules",
  "Displays - Character LCD",
  "Displays - Graphic LCD & TFT",
  "Displays - OLED",
  "Displays - E-Paper",
  "Logic ICs (74xx/4000)",
  "Flip-Flops & Latches",
  "Shift Registers & Counters",
  "Level Shifters & Digital Isolators",
  "Interface ICs (RS-232/RS-485/CAN/LIN)",
  "USB Interface ICs",
  "Ethernet Controllers & Modules",
  "Wireless Modules - Wi-Fi",
  "Wireless Modules - Bluetooth",
  "Wireless Modules - Zigbee/Thread",
  "Wireless Modules - Sub-GHz RF",
  "GNSS/GPS Modules",
  "Antennas & RF Connectors",
  "Microcontrollers",
  "FPGA & CPLD",
  "Development Boards & Kits",
  "Single-Board Computers",
  "Breakout Boards",
  "Shields & HATs",
  "Relays (Electromechanical)",
  "Solid-State Relays",
  "Switches - Tactile & Pushbutton",
  "Switches - Toggle & Rocker",
  "Switches - DIP & Slide",
  "Switches - Limit & Reed",
  "Rotary Encoders & Keypads",
  "Motors",
  "Motor Drivers & H-Bridges",
  "Solenoids & Actuators",
  "Sensors",
  "Connectors - Pin Headers & Sockets",
  "Connectors - JST & Crimp",
  "Connectors - Dupont Jumper",
  "Connectors - Terminal Blocks",
  "Connectors - IDC & Ribbon",
  "Connectors - USB",
  "Connectors - Barrel Jack & DC Plug",
  "Connectors - RJ45 Ethernet",
  "Connectors - RF (SMA/u.FL)",
  "Cables - Jumper Wires",
  "Cables - Hook-Up Wire",
  "Cables - Ribbon Cable",
  "Adapters - Power & Signal",
  "Heat-Shrink & Sleeving",
  "Cable Management",
  "Heatsinks & Thermal Interface Materials",
  "Enclosures",
  "DIN Rail & Accessories",
  "Mounting Hardware (Standoffs/Screws/Nuts)",
  "Breadboards",
  "Perfboard & Stripboard",
  "Proto PCBs & Shields",
  "Solder & Flux",
  "Solder Paste & Stencils",
  "Chemicals (IPA/Flux Remover)",
  "Memory - EEPROM & Flash",
  "Memory Cards & Sockets",
  "Programmers & Debuggers"
]
